import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>APISetu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://img1.digitallocker.gov.in/ndh/smart/images/apisetu_icon.png" />
      </Head>
      <Hero />
    </div>
  )
}
